Repository lion-packages/helpers, pull requests merged in 2025-04, with the labels that each got.

#17 Integrate Dependency-Review
  .github/workflows/php.yml
Labels: continuous integration

#18 Integrate PHPLint
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration

#19 Add Dependabot configuration
  .github/dependabot.yml
Labels: continuous integration

#21 Update README.md
  .github/README.md
Labels: documentation

#22 The infection library is installed
  composer.json
  infection.json
  phpunit.xml
  src/LionHelpers/Arr.php
  src/LionHelpers/Str.php
  tests/ArrTest.php
  tests/StrTest.php
Labels: dependencies, tests

#24 Apply fixes from StyleCI
  tests/Providers/ArrProviderTrait.php
Labels: enhancement

#25 Added StyleCI configuration
  .styleci.yml
  tests/Providers/ArrProviderTrait.php
Labels: continuous integration, standardization

#26 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#27 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#28 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#29 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration
